
--MAKES WEEK 1 Start on 1/1/23 and WEEK 2 Starts on 1/2/22 (Sun-Sat Reporting Period).
alter session set week_start = 7;
alter session set week_of_year_policy = 1;


--Site UU Query
SELECT   
        week(EVENT_DATE) as week,
        year(EVENT_DATE) as year,
        COUNT(distinct ADJUSTED_UU_ID) As total_UU_counts, 
        COUNT(DISTINCT(CASE WHEN IS_DIGITAL_BRAND_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE  NULL END)) AS Digital_Brand,
        COUNT(DISTINCT(CASE WHEN IS_DIRECT_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Direct,
        COUNT(DISTINCT(CASE WHEN IS_DISPLAY_SOCIALADS_VISITOR = 1 or IS_PAID_SOCIAL_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Disp_Paid_Social,
        COUNT(DISTINCT(CASE WHEN IS_EMAIL_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Email,
        COUNT(DISTINCT(CASE WHEN IS_NOTIFICATIONS_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Notifications,
        COUNT(DISTINCT(CASE WHEN IS_ORGANIC_SEARCH_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Organic_Search,
        COUNT(DISTINCT(CASE WHEN IS_ORGANIC_SOCIAL_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Organic_Social,
        COUNT(DISTINCT(CASE WHEN IS_MISCSOURCES_VISITOR = 1 or IS_SESSION_REFRESH_VISITOR = 1 or IS_OTHER_CAMPAIGNS_VISITOR = 1 or IS_MOBILE_UNKNOWN_VISITOR = 1 or IS_OWNED_CROSS_PLATFORM_VISITOR = 1 or IS_PARTNER_VISITOR = 1 or IS_AFFILIATE_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Others,
        COUNT(DISTINCT(CASE WHEN IS_PAID_SEARCH_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Paid_Search,
        COUNT(DISTINCT(CASE WHEN IS_MISCSOURCES_VISITOR = 1 or IS_SESSION_REFRESH_VISITOR = 1 or IS_DIGITAL_BRAND_VISITOR = 1 or IS_OTHER_CAMPAIGNS_VISITOR = 1 or IS_MOBILE_UNKNOWN_VISITOR = 1 or IS_OWNED_CROSS_PLATFORM_VISITOR = 1 or IS_PARTNER_VISITOR = 1 or IS_AFFILIATE_VISITOR = 1 or IS_ORGANIC_SEARCH_VISITOR = 1 or IS_DIRECT_VISITOR = 1 or IS_ORGANIC_SOCIAL_VISITOR = 1 or IS_NOTIFICATIONS_VISITOR = 1 or IS_PAID_SEARCH_VISITOR = 1 or IS_EMAIL_VISITOR = 1 or IS_DISPLAY_SOCIALADS_VISITOR = 1 or IS_PAID_SOCIAL_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Weekly_Total_UUs
 FROM "RDC_ANALYTICS"."CLICKSTREAM"."UNIQUE_USERS_DAILY"
        where EVENT_DATE >= '2023-10-22'
        and IS_FOR_RENT_VISITOR = 1  
        GROUP BY 1,2
        ORDER BY 1,2



--MAKES WEEK 1 Start on 1/1/23 and WEEK 2 Starts on 1/2/22 (Sun-Sat Reporting Period).
alter session set week_start = 7;
alter session set week_of_year_policy = 1;

--For Sale Leads
select --LEAD_SUBMITTED_DATE,
week(LEAD_SUBMITTED_DATE), 
COUNT(SUBMITTED_LEAD_ID) as For_Sale_Leads,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'direct (typed/bookmarked)' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Direct,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'display/social ads' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Disp_Paid_Social,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'email' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Email,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'notifications' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Notifications,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'organic search' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Organic_Search,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'organic social' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Organic_Social,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'misc sources' or LAST_TOUCH_MARKETING_CHANNEL = 'session refresh' or LAST_TOUCH_MARKETING_CHANNEL = 'digital brand' or LAST_TOUCH_MARKETING_CHANNEL = 'other campaigns' or LAST_TOUCH_MARKETING_CHANNEL = 'mobile unknown' or LAST_TOUCH_MARKETING_CHANNEL = 'owned cross platform' or LAST_TOUCH_MARKETING_CHANNEL = 'partner' or LAST_TOUCH_MARKETING_CHANNEL = 'referring domains' or LAST_TOUCH_MARKETING_CHANNEL is NULL or LAST_TOUCH_MARKETING_CHANNEL = 'unknown' or LAST_TOUCH_MARKETING_CHANNEL = 'affiliates' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Others,
COUNT(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'paid search' THEN SUBMITTED_LEAD_ID ELSE NULL END) as Paid_Search
from "RDC_ANALYTICS"."LEADS"."SUBMITTED_LEAD_DETAIL"
where year(LEAD_SUBMITTED_DATE) >= '2023'
and week(LEAD_SUBMITTED_DATE) >= '40'
--and PLATFORM = 'iOS App'
and LEAD_VERTICAL = 'for_sale'
group by 1--,2
order by 1



--MAKES WEEK 1 Start on 1/1/23 and WEEK 2 Starts on 1/2/22 (Sun-Sat Reporting Period).
alter session set week_start = 7;
alter session set week_of_year_policy = 1;


--For Sale EFR MCD
select --event_date,
week(event_date), 
SUM(estimated_future_revenue) as EFR,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'direct (typed/bookmarked)' THEN estimated_future_revenue ELSE NULL END) as Direct,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'display/social ads' THEN estimated_future_revenue ELSE NULL END) as Disp_Paid_Social,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'email' THEN estimated_future_revenue ELSE NULL END) as Email,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'notifications' THEN estimated_future_revenue ELSE NULL END) as Notifications,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'organic search' THEN estimated_future_revenue ELSE NULL END) as Organic_Search,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'organic social' THEN estimated_future_revenue ELSE NULL END) as Organic_Social,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'misc sources' or LAST_TOUCH_MARKETING_CHANNEL = 'session refresh' or LAST_TOUCH_MARKETING_CHANNEL = 'digital brand' or LAST_TOUCH_MARKETING_CHANNEL = 'other campaigns' or LAST_TOUCH_MARKETING_CHANNEL = 'mobile unknown' or LAST_TOUCH_MARKETING_CHANNEL = 'owned cross platform' or LAST_TOUCH_MARKETING_CHANNEL = 'partner' or LAST_TOUCH_MARKETING_CHANNEL = 'referring domains' or LAST_TOUCH_MARKETING_CHANNEL is NULL or LAST_TOUCH_MARKETING_CHANNEL = 'unknown' or LAST_TOUCH_MARKETING_CHANNEL = 'affiliates' THEN estimated_future_revenue ELSE NULL END) as Others,
SUM(Case WHEN LAST_TOUCH_MARKETING_CHANNEL = 'paid search' THEN estimated_future_revenue ELSE NULL END) as Paid_Search
from "RDC_ANALYTICS"."REVENUE"."MARKETING_CONVERSION_DETAIL"
where year(event_date) = '2023'
and week(event_date) >= '42'
and lower(submitted_lead_vertical) = 'for_sale'
group by 1--,2
order by 1



--MAKES WEEK 1 Start on 1/2/23 and 1/3/22 (Mon-Sun Reporting Period). 
alter session set week_start = 1;
alter session set week_of_year_policy = 1;

        
--Rentals UU Query
SELECT   
        week(EVENT_DATE) as week,
        year(EVENT_DATE) as year,
        COUNT(distinct ADJUSTED_UU_ID) As total_UU_counts, 
        COUNT(DISTINCT(CASE WHEN IS_DIRECT_VISITOR = 1 THEN 
ADJUSTED_UU_ID ELSE NULL END)) AS Direct,
        COUNT(DISTINCT(CASE WHEN IS_DISPLAY_SOCIALADS_VISITOR = 1 or
IS_PAID_SOCIAL_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS 
Disp_Paid_Social,
        COUNT(DISTINCT(CASE WHEN IS_EMAIL_VISITOR = 1 THEN 
ADJUSTED_UU_ID ELSE NULL END)) AS Email,
        COUNT(DISTINCT(CASE WHEN IS_NOTIFICATIONS_VISITOR = 1 THEN 
ADJUSTED_UU_ID ELSE NULL END)) AS Notifications,
        COUNT(DISTINCT(CASE WHEN IS_ORGANIC_SEARCH_VISITOR = 1 
THEN ADJUSTED_UU_ID ELSE NULL END)) AS Organic_Search,
        COUNT(DISTINCT(CASE WHEN IS_ORGANIC_SOCIAL_VISITOR = 1 
THEN ADJUSTED_UU_ID ELSE NULL END)) AS Organic_Social,
        COUNT(DISTINCT(CASE WHEN IS_MISCSOURCES_VISITOR = 1 or 
IS_SESSION_REFRESH_VISITOR = 1 or IS_DIGITAL_BRAND_VISITOR = 1 or IS_OTHER_CAMPAIGNS_VISITOR = 1 or IS_MOBILE_UNKNOWN_VISITOR = 1 or 
IS_OWNED_CROSS_PLATFORM_VISITOR = 1 or IS_PARTNER_VISITOR = 1 or IS_AFFILIATE_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Others,
        COUNT(DISTINCT(CASE WHEN IS_PAID_SEARCH_VISITOR = 1 THEN 
ADJUSTED_UU_ID ELSE NULL END)) AS Paid_Search,
        COUNT(DISTINCT(CASE WHEN IS_MISCSOURCES_VISITOR = 1 or 
IS_SESSION_REFRESH_VISITOR = 1 or IS_DIGITAL_BRAND_VISITOR = 1 or IS_OTHER_CAMPAIGNS_VISITOR = 1 or IS_MOBILE_UNKNOWN_VISITOR = 1 or 
IS_OWNED_CROSS_PLATFORM_VISITOR = 1 or IS_PARTNER_VISITOR = 1 or IS_AFFILIATE_VISITOR = 1 or IS_ORGANIC_SEARCH_VISITOR = 1 or IS_DIRECT_VISITOR = 1 or IS_ORGANIC_SOCIAL_VISITOR = 1 or IS_NOTIFICATIONS_VISITOR = 1 or IS_PAID_SEARCH_VISITOR = 1 or IS_EMAIL_VISITOR = 1 or IS_DISPLAY_SOCIALADS_VISITOR = 1 or IS_PAID_SOCIAL_VISITOR = 1 THEN ADJUSTED_UU_ID ELSE NULL END)) AS Weekly_Total_UUs
 FROM "RDC_ANALYTICS"."CLICKSTREAM"."UNIQUE_USERS_DAILY"
        where EVENT_DATE >= '2023-10-08'
        and IS_FOR_RENT_VISITOR = 1  
        GROUP BY 1,2
        ORDER BY 1,2